// Project: NeuraRig
// Copyright (c) 2026 Rafael Valoto
// All rights reserved.
#pragma once

#include "NRCore/NRTypes.h"
#include "NRInterfaces/INRModel.h"
#include <vector>

#include "NRCore/NRRules.h"
#include "NRNetwork/NRNetwork.h"

namespace NR
{
	template<FloatingPoint T = float>
	class NRTrainee
	{
		std::shared_ptr<INRModel<T> > TargetModel;
		std::unique_ptr<torch::optim::Adam> Optimizer;
		NRModelProfile RigDesc;
		NRRules Evaluator;
		NRNetwork Network;

		/**
		 * Calculates the next rotation for a given trainee in a training schedule.
		 *
		 * @param TargetModel The current trainee's identifier.
		 * @param Rig The list of all trainees in the schedule.
		 * @param LearningRate The step or interval to determine the next trainee.
		 */
	public:
		torch::Tensor IdealTarg;

		NRTrainee(std::shared_ptr<INRModel<T> > TargetModel, NRModelProfile Rig, NRRules Ev, double LearningRate = 1e-3);

		void SaveWeights(const std::string& Path);

		void LoadWeights(const std::string& Path);

		/**
		 * Executes the next step in the training process by determining the current stage.
		 *
		 * @param InputFloats The dataset being used for the training process.
		 * @return A flag indicating whether the training step was successfully completed.
		 */
		float TrainStep(const std::vector<float>& InputFloats);

		/**
		 * Computes the Inverse Kinematics (IK) loss for a given model configuration.
		 *
		 * @param Input The predicted pose generated by the model.
		 * @param Pred The target pose to compare against.
		 * @return IKLossResult
		 */
		IKLossResult ComputeRLReward(const torch::Tensor& Input, const torch::Tensor& Pred);

		torch::Tensor NormalizeQuats(const torch::Tensor& q)
		{
			auto norm = q.norm(2, 1, true);
			return q / (norm + 1e-8);
		}

		// q = (x, y, z, w)
		torch::Tensor QuatMultiply(const torch::Tensor& q1, const torch::Tensor& q2)
		{
			auto x1 = q1.select(1, 0), y1 = q1.select(1, 1);
			auto z1 = q1.select(1, 2), w1 = q1.select(1, 3);
			auto x2 = q2.select(1, 0), y2 = q2.select(1, 1);
			auto z2 = q2.select(1, 2), w2 = q2.select(1, 3);

			auto w = w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2;
			auto x = w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2;
			auto y = w1 * y2 - x1 * z2 + y1 * w2 + z1 * x2;
			auto z = w1 * z2 + x1 * y2 - y1 * x2 + z1 * w2;

			return torch::stack({x, y, z, w}, 1);
		}

		torch::Tensor QuatRotateVector(const torch::Tensor& q, const torch::Tensor& v)
		{
			auto qw = q.select(1, 3).unsqueeze(1);
			auto qvec = q.slice(1, 0, 3);

			// t = 2 * cross(qvec, v)
			auto t = 2.0f * torch::linalg_cross(qvec, v, 1);

			// result = v + qw * t + cross(qvec, t)
			return v + qw * t + torch::linalg_cross(qvec, t, 1);
		}

	};
} // namespace NR
