// Project: NeuraRig
// Copyright (c) 2026 Rafael Valoto
// All rights reserved.
#pragma once

#include "NRCore/NRTypes.h"
#include "NRInterfaces/INRModel.h"
#include <vector>

namespace NR
{
	template<FloatingPoint T = float>
	class NRTrainee
	{
		std::shared_ptr<INRModel<T> > TargetModel;
		std::unique_ptr<torch::optim::Adam> Optimizer;
		NRModelProfile RigDesc;

		/**
		 * Calculates the next rotation for a given trainee in a training schedule.
		 *
		 * @param TargetModel The current trainee's identifier.
		 * @param Rig The list of all trainees in the schedule.
		 * @param LearningRate The step or interval to determine the next trainee.
		 */
	public:
		NRTrainee(std::shared_ptr<INRModel<T> > TargetModel, NRModelProfile Rig, double LearningRate = 1e-3);

		void SaveWeights(const std::string& Path);

		void LoadWeights(const std::string& Path);

		/**
		 * Executes the next step in the training process by determining the current stage.
		 *
		 * @param InputFloats The dataset being used for the training process.
		 * @return A flag indicating whether the training step was successfully completed.
		 */
		float TrainStep(const std::vector<float>& InputFloats);

		/**
		 * Computes the Inverse Kinematics (IK) loss for a given model configuration.
		 *
		 * @param Input The predicted pose generated by the model.
		 * @param PredQuats The target pose to compare against.
		 */
		IKLossResult ComputeRLReward(const torch::Tensor& Input, const torch::Tensor& Pred);

		FKResult ForwardKinematicsChain(
			const torch::Tensor& ThighOffset,
			float L1,
			float L2,
			const torch::Tensor& ThighQuat,
			const torch::Tensor& CalfQuat,
			const torch::Tensor& Axis);


		AnalyticResult SolveAnalyticIK(
			const torch::Tensor& HipPos,
			const torch::Tensor& TargetPos,
			float L1, float L2,
			const torch::Tensor& Axis,
			const torch::Tensor& Axis2,
			const torch::Tensor& PoleVec);

		torch::Tensor QuatFromAxisAngle(const torch::Tensor& Axis, const torch::Tensor& Angle)
		{
			auto angleReshaped = Angle.view({-1, 1});

			auto halfAngle = angleReshaped * 0.5f;
			auto s = torch::sin(halfAngle); // [Batch, 1]
			auto c = torch::cos(halfAngle); // [Batch, 1]

			// Axis é [Batch, 3], s é [Batch, 1] -> Resultado [Batch, 3]
			auto xyz = Axis * s;

			// Concatena [Batch, 3] com [Batch, 1] no eixo 1 -> [Batch, 4]
			return torch::cat({xyz, c}, 1);
		}

		torch::Tensor QuatLookAt(const torch::Tensor& SourceDir, const torch::Tensor& TargetDir) {
			// Calcula o eixo de rotação (produto vetorial entre onde o osso aponta e onde deve apontar)
			auto source = SourceDir / (torch::norm(SourceDir, 2, 1, true) + 1e-6f);
			auto target = TargetDir / (torch::norm(TargetDir, 2, 1, true) + 1e-6f);

			auto dot = torch::sum(source * target, 1, true);

			// Se o dot for -1, os vetores são opostos (rotação de 180 graus)
			// Se o dot for 1, já estão alinhados
			auto cross = torch::linalg_cross(source, target);
			auto w = 1.0f + dot;

			// Constrói o Quaternion e normaliza
			auto q = torch::cat({cross, w}, 1);
			return q / (torch::norm(q, 2, 1, true) + 1e-6f);
		}

		torch::Tensor NormalizeQuats(const torch::Tensor& q)
		{
			auto norm = q.norm(2, 1, true);
			return q / (norm + 1e-8f);
		}

		// q = (x, y, z, w)
		torch::Tensor QuatMultiply(const torch::Tensor& q1, const torch::Tensor& q2)
		{
			auto x1 = q1.select(1, 0), y1 = q1.select(1, 1);
			auto z1 = q1.select(1, 2), w1 = q1.select(1, 3);
			auto x2 = q2.select(1, 0), y2 = q2.select(1, 1);
			auto z2 = q2.select(1, 2), w2 = q2.select(1, 3);

			auto w = w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2;
			auto x = w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2;
			auto y = w1 * y2 - x1 * z2 + y1 * w2 + z1 * x2;
			auto z = w1 * z2 + x1 * y2 - y1 * x2 + z1 * w2;

			return torch::stack({x, y, z, w}, 1);
		}

		torch::Tensor QuatRotateVector(const torch::Tensor& q, const torch::Tensor& v)
		{
			auto qw = q.select(1, 3).unsqueeze(1);
			auto qvec = q.slice(1, 0, 3);

			// t = 2 * cross(qvec, v)
			auto t = 2.0f * torch::linalg_cross(qvec, v, 1);

			// result = v + qw * t + cross(qvec, t)
			return v + qw * t + torch::linalg_cross(qvec, t, 1);
		}

		// --- ESPECIALISTA 1: A FÓRMULA (O PROFESSOR) ---
		torch::Tensor GetTeacherReward(const AnalyticResult& Guide, const torch::Tensor& pThigh, const torch::Tensor& pCalf)
		{
			auto QuatMSE = [](torch::Tensor p, torch::Tensor g) {
				auto dot = torch::sum(p * g, 1, true);
				return torch::mse_loss(p, torch::where(dot < 0, -g, g));
			};
			return (QuatMSE(pThigh, Guide.ThighQuat) + QuatMSE(pCalf, Guide.CalfQuat)) * 0.5f;
		}

		// --- ESPECIALISTA 2: O ESPAÇO 3D (O ENGENHEIRO) ---
		torch::Tensor GetPrecisionReward(const torch::Tensor& FootPos, const torch::Tensor& TargetPos)
		{
			return torch::mse_loss(FootPos, TargetPos);
		}

		// --- ESPECIALISTA 3: A FÍSICA (O BIÓLOGO) ---
		torch::Tensor GetConstraintsReward(const torch::Tensor& pCalf, const torch::Tensor& Axis)
		{
			auto KneeDir = QuatRotateVector(pCalf, Axis);
			auto Alignment = torch::dot(KneeDir.flatten(), Axis.flatten());
			return torch::relu(-Alignment); // Penaliza se o joelho inverter
		}


	};
} // namespace NR
